# Generated by Django 5.2.4 on 2026-05-06 18:23

from django.db import migrations


def seed_data(apps, schema_editor):
    Material = apps.get_model('factory_admin', 'Material')
    Inventory = apps.get_model('factory_admin', 'Inventory')

    materials_data = [
        {'name': 'Iron', 'price_per_unit': 60, 'qty': 1000},
        {'name': 'Steel', 'price_per_unit': 80, 'qty': 800},
        {'name': 'Wood', 'price_per_unit': 50, 'qty': 500},
        {'name': 'Glass', 'price_per_unit': 120, 'qty': 300},
        {'name': 'Aluminium', 'price_per_unit': 500, 'qty': 1500}, # Keeping existing ones
        {'name': 'uPVC', 'price_per_unit': 400, 'qty': 1200},
    ]

    for data in materials_data:
        mat, created = Material.objects.get_or_create(
            name__iexact=data['name'],
            defaults={'name': data['name'], 'price_per_unit': data['price_per_unit']}
        )
        
        inv, inv_created = Inventory.objects.get_or_create(
            material=mat,
            defaults={'quantity': data['qty']}
        )

def reverse_seed_data(apps, schema_editor):
    Material = apps.get_model('factory_admin', 'Material')
    materials = ['Iron', 'Steel', 'Wood', 'Glass', 'Aluminium', 'uPVC']
    # Inventory will be deleted via cascade
    for mat_name in materials:
        Material.objects.filter(name__iexact=mat_name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('factory_admin', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed_data),
    ]
