# Generated by Django 5.2.4 on 2026-05-06 18:30

from django.db import migrations, models

def seed_dimension_config(apps, schema_editor):
    DimensionConfig = apps.get_model('factory_admin', 'DimensionConfig')
    configs = [
        {'type': 'window', 'min_w': 300, 'max_w': 3000, 'min_h': 300, 'max_h': 3000},
        {'type': 'door', 'min_w': 600, 'max_w': 1500, 'min_h': 1800, 'max_h': 3000},
    ]
    for conf in configs:
        DimensionConfig.objects.get_or_create(
            design_type=conf['type'],
            defaults={
                'min_width': conf['min_w'],
                'max_width': conf['max_w'],
                'min_height': conf['min_h'],
                'max_height': conf['max_h'],
            }
        )

def reverse_dimension_config(apps, schema_editor):
    DimensionConfig = apps.get_model('factory_admin', 'DimensionConfig')
    DimensionConfig.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('factory_admin', '0002_seed_default_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_type', models.CharField(choices=[('window', 'Window'), ('door', 'Door')], max_length=20, unique=True)),
                ('min_width', models.FloatField(default=300)),
                ('max_width', models.FloatField(default=3000)),
                ('min_height', models.FloatField(default=300)),
                ('max_height', models.FloatField(default=3000)),
            ],
        ),
        migrations.RunPython(seed_dimension_config, reverse_dimension_config),
    ]
